version: '3'

services:
  quarkus:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://db:5433/savestment
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
  db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=savestment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5