drop table if exists SAVESTMENT_USERS;
drop table if exists INVESTMENT_TYPES;
drop table if exists INVESTMENT_ITEMS;
drop table if exists EXPENDITURE_TYPE;
drop table if exists EXPENDITURE_CATEGORY;
drop table if exists EXPENDITURE;

CREATE TABLE IF NOT EXISTS INVESTMENT_TYPES
(
    INVESTMENT_TYPE_ID BIGSERIAL PRIMARY KEY,
    INVESTMENT_NAME VARCHAR(100) NOT NULL,
    CREATED_ON TIMESTAMPTZ NOT NULL,
    UPDATED_ON TIMESTAMPTZ NOT NULL
);


CREATE TABLE IF NOT EXISTS INVESTMENT_ITEMS
(
    INVESTMENT_ID BIGSERIAL PRIMARY KEY,
    INVESTMENT_TYPE_ID BIGSERIAL,
    SYMBOL VARCHAR(100) NOT NULL,
    TRADE_DATE DATE NOT NULL,
    TRADE_TYPE VARCHAR(8) NOT NULL,
    UNITS NUMERIC NOT NULL,
    PRICE NUMERIC NOT NULL,
    AMOUNT_INVESTED NUMERIC NOT NULL,
    CREATED_BY UUID,
    CREATED_ON TIMESTAMPTZ NOT NULL,
    UPDATED_ON TIMESTAMPTZ NOT NULL,
    CONSTRAINT FK_INVESTMENT_TYPE_ID FOREIGN KEY(INVESTMENT_TYPE_ID) REFERENCES INVESTMENT_TYPES(INVESTMENT_TYPE_ID),
    CONSTRAINT FK_CREATED_BY FOREIGN KEY(CREATED_BY) REFERENCES SAVESTMENT_USERS(USER_UID)
);

CREATE TABLE IF NOT EXISTS EXPENDITURE_TYPE
(
    EXPENDITURE_TYPE_ID BIGSERIAL PRIMARY KEY,
    EXPENDITURE_NAME VARCHAR(100) NOT NULL,
    CREATED_ON TIMESTAMPTZ NOT NULL,
    UPDATED_ON TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS EXPENDITURE_CATEGORY
(
    EXPENDITURE_CATEGORY_ID BIGSERIAL PRIMARY KEY,
    EXPENDIURE_TYPE_ID BIGSERIAL,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    CREATED_BY UUID,
    CREATED_ON TIMESTAMPTZ NOT NULL,
    UPDATED_ON TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS EXPENDITURE
(
    EXPENDITURE_ID BIGSERIAL PRIMARY KEY,
    EXPENDITURE_CATEGORY_ID BIGSERIAL,
    EXPENDITURE_AMOUNT NUMERIC NOT NULL,
    EXPENDITURE_DESCRIPTION VARCHAR(500),
    MODE_OF_PAYMENT PAYMODE NOT NULL,
    DATE_OF_EXPENDITURE TIMESTAMPTZ,
    CREATED_BY UUID,
    CREATED_ON TIMESTAMPTZ NOT NULL,
    UPDATED_ON TIMESTAMPTZ NOT NULL
);

